# Default values for viper based services

#possible values are ui and backend
project:
  type: ui
  includeAwsCredentials: false

#-------------------------------#
# deployment.yaml value section #
#-------------------------------#

replicas: 2

image:
  repository:
  tag: latest
  pullPolicy: Always

connection:
  https:
    port: 443



#-------------------------------#
# ingress.yaml value section    #
#-------------------------------#

ingress:
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  path: /
  hosts:
  servicePort: 443



#-------------------------------#
# service.yaml value section    #
#-------------------------------#

service:
  spec:
    type: ClusterIP
    ports:
      https: 443
      targetPort: 443



#-------------------------------#
# secret.yaml value section     #
#-------------------------------#
secret:
    aws_accesskey:
    aws_secretkey:
    keystore:
    password:
    ui_crt:
    ui_key: