{{- $serviceName := include "service.name" . -}}

{{- if .Values.oauth2.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serviceName }}-auth-sidecar
data:
  {{- range $key, $value := .Values.oauth2.sidecar.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.oauth2.cache }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.additionalparameters.configMapApplied}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serviceName }}-additional-parametes
data:
  {{- range $key, $value := .Values.additionalparameters.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.additionalparameters.yamlConfigFileApplied -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serviceName }}-additional-config-yaml
data:
  config.yaml: |-
    {{- toYaml .Values.additionalparameters.yamlConfigFile | nindent 4 }}
{{- end -}}
