apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.name" . }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "service.name" . }}
    spec:
      imagePullSecrets:
        - name: aws-ecr-secret
      containers:
        - name: {{ include "service.name" . }}
          image: {{ include "image.url" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.project.includeAwsCredentials }}
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "service.name" . }}-secret
                  key: aws.accesskey
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "service.name" . }}-secret
                  key: aws.secretkey
            {{- end}}
          ports:
            - containerPort: {{ .Values.connection.http.port }}
              name: http
              protocol: TCP