{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressServicePort := .Values.ingress.servicePort -}}
{{- $serviceName := include "service.name" . -}}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "service.name" . }}-ing
  {{- with .Values.ingress.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . | quote }}
    http:
      paths:
        - path: {{ $ingressPath }}
          backend:
            serviceName: {{ $serviceName }}-svc
            servicePort: {{ $ingressServicePort }}
  {{- end }}