{{- $ingressExtPath := .Values.ingress.ext.path -}}
{{- $ingressExtServicePort := .Values.ingress.ext.servicePort -}}
{{- $ingressIntPath := .Values.ingress.int.path -}}
{{- $ingressIntServicePort := .Values.ingress.int.servicePort -}}
{{- $serviceName := include "service.name" . -}}

{{- if .Values.ingress.ext.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $serviceName }}-ing-ext
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.ext.class | quote }}
    cert-manager.io/issuer: {{ .Values.tls.issuer.name | quote }}
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.ext.annotations.ssl.redirect }}
    nginx.ingress.kubernetes.io/ssl-ciphers: {{ .Values.ingress.ext.annotations.ssl.ciphers }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.ext.host | quote }}
      secretName: {{ .Values.tls.cert.ext.secret.name }}
  rules:
    - host: {{ .Values.ingress.ext.host }}
      http:
        paths:
          - path: {{ $ingressExtPath }}
            backend:
              serviceName: {{ $serviceName }}-svc
              servicePort: {{ $ingressExtServicePort }}
{{- end }}

{{- if .Values.ingress.int.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $serviceName }}-ing-int
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.int.class | quote }}
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.int.annotations.ssl.redirect }}
    nginx.ingress.kubernetes.io/ssl-ciphers: {{ .Values.ingress.int.annotations.ssl.ciphers }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.int.host | quote }}
      secretName: {{ $serviceName }}-{{ .Values.tls.cert.int.secret.name }}
  rules:
    - host: {{ .Values.ingress.int.host }}
      http:
        paths:
          - path: {{ $ingressIntPath }}
            backend:
              serviceName: {{ $serviceName }}-svc
              servicePort: {{ $ingressIntServicePort }}
{{- end }}
