apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.name" . }}-secret
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.project.includeAwsCredentials }}
  aws.accesskey: {{ .Values.secret.aws_accesskey }}
  aws.secretkey: {{ .Values.secret.aws_secretkey }}
  {{- end }}
type: Opaque