{{- $serviceName := include "service.name" . -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}-secret
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.project.includeAwsCredentials }}
  aws.accesskey: {{ .Values.secret.aws_accesskey }}
  aws.secretkey: {{ .Values.secret.aws_secretkey }}
  {{- end }}
type: Opaque

{{- if .Values.ingress.int.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}-{{ .Values.tls.cert.int.secret.name }}
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ .Values.tls.cert.int.secret.crt }}
  tls.key: {{ .Values.tls.cert.int.secret.key }}
type: kubernetes.io/tls
{{- end }}

{{- if .Values.oauth2.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}-auth-sidecar
type: Opaque
data:
  {{- range $key, $value := .Values.oauth2.secret }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}


---
{{- if .Values.additionalparameters.secretsApplied }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}-additional-secrets
type: Opaque
data:
  {{- range $key, $value := .Values.additionalparameters.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
