apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.name" . }}-secret
data:
  keystore.p12: >-
    {{ .Values.secret.keystore }}
  password: {{ .Values.secret.password }}
  aws.accesskey: {{ .Values.secret.aws_accesskey }}
  aws.secretkey: {{ .Values.secret.aws_secretkey }}
type: Opaque