---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.name" . }}-secret
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.project.includeAwsCredentials }}
  aws.accesskey: {{ .Values.secret.aws_accesskey }}
  aws.secretkey: {{ .Values.secret.aws_secretkey }}
  {{- end }}
type: Opaque

{{- if .Values.ingress.int.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.cert.int.secret.name }}
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ .Values.tls.cert.int.secret.crt }}
  tls.key: {{ .Values.tls.cert.int.secret.key }}
type: kubernetes.io/tls
{{- end }}