apiVersion: v1
kind: Secret
metadata:
  name: {{ include "service.name" . }}-secret
  namespace: {{ .Values.namespace.name }}
data:
  {{- if .Values.project.includeAwsCredentials }}
  aws.accesskey: {{ .Values.secret.aws_accesskey }}
  aws.secretkey: {{ .Values.secret.aws_secretkey }}
  {{- end }}
  {{- if eq .Values.project.type "ui"  }}
  ui.crt: {{ .Values.secret.ui_crt }}
  ui.key: {{ .Values.secret.ui_key }}
  {{- end }}
type: Opaque