{{- $serviceName := include "service.name" . -}}

---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ $serviceName }}-service-secrets
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  dataFrom:
    - {{ .Values.externalSecret.service.credentials.key }}

  {{- if .Values.ingress.int.enabled }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ $serviceName }}-{{ .Values.tls.cert.int.secret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  dataFrom:
    - {{ .Values.tls.cert.int.secret.value }}
  template:
    type: kubernetes.io/tls
  {{- end }}

  {{- if .Values.additionalparameters.secretsApplied }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $serviceName }}-additional-secrets
type: Opaque
data:
  {{- range $key, $value := .Values.additionalparameters.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}

  {{- if .Values.oauth2.enabled }}
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ $serviceName }}-auth-sidecar
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  dataFrom:
    - {{ .Values.oauth2.sidecar.secret.key }}
  {{- end}}
