apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.name" . }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.spec.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.spec.ports.http }}
      targetPort: {{ .Values.service.spec.ports.targetPort }}
  selector:
    app: {{ include "service.name" . }}