{{- $serviceName := include "service.name" . -}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.spec.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.spec.ports.http }}
{{- if .Values.oauth2.enabled }}
      targetPort: {{ .Values.oauth2.sidecar.servicePort }}
{{- else }}
      targetPort: {{ .Values.service.spec.ports.targetPort }}
{{- end }}
  selector:
    app: {{ $serviceName }}
