---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: {{ .Values.tls.issuer.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selfSigned: {}

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: {{ .Values.namespace.name }}
spec:
  commonName: {{ .Values.ingress.host | quote }}
  secretName: {{ .Values.tls.cert.secret_name }}
  issuerRef:
    name: {{ .Values.tls.issuer.name }}