---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ .Values.tls.issuer.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: {{ .Values.namespace.name }}
spec:
  dnsNames:
    - {{ .Values.ingress.host | quote }}
  secretName: {{ .Values.tls.cert.secret_name }}
  issuerRef:
    name: {{ .Values.tls.issuer.name }}